### ISSUE TITLE
step "Adding cover art" uses wrong path "Hörbuch" instead of "Audiobook"

### ISSUE THREAD

**Issue by johr** [Sebelino/aax-to-mp3#5]
I tried to convert an aax file. According to the logs all was fine till the step when "Adding cover art" was done.

`aaxtomp3 stdout: Adding cover art

aaxtomp3 closed with exit code 1
node:fs:1451
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/tmp/aax2mp3/Audiobook'
    at Object.readdirSync (node:fs:1451:3)
    at processMp3Files (/usr/src/app/server.js:115:23)
    at ChildProcess.<anonymous> (/usr/src/app/server.js:154:9)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:321:12) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/tmp/aax2mp3/Audiobook'
}
`

A mapped a volume to the container and checked the content. There was not /tmp/aax2mp3/Audiobook but /tmp/ax2mp3/Hörbuch (which is german for Audiobook).
It is a german audiobook, so that could be the reason for having "Hörbuch" in the path. I don't know if this could be handled somehow.

**Comment by Sebelino** [comment]
Hi, thanks for reporting. I have released [a fix](https://github.com/Sebelino/aax-to-mp3/commit/4a1be477f52efcd3c56b72ebd5b8d5f104573543). Could you verify that it resolves the issue?
```
$ docker run -p 80:80 sebelino/aax-to-mp3:v1.2.1
```

**Comment by johr** [comment]
now it works producing a single mp3 file with the cover. 
then i manually call /download with the browser (firefox) and it gets downloaded. no automatic download as mentioned in the readme.

**Comment by Sebelino** [comment]
OK interesting, it downloads automatically for me on both Chromium and Firefox. In any case, I added a note about it now. https://github.com/Sebelino/aax-to-mp3/commit/d8c7f917016aea6669808e58833b991806bdd796

Thank you for verifying.

**Comment by johr** [comment]
what it does, when pushing the convert-button: it immediately goes to /output and stays there. if this helps.
but anyway, if one knows, its easy to just call /download.
thanks.
